### ISSUE TITLE
Support request: Publishing of other MQTT data on FLM broker (from Ra-Pie)

### ISSUE THREAD

**Issue by Ryton** [gebhardm/energyhacks#1]
Hi there,

Could you give me some pointers, as how to get a r-pi to publish a MQTT message to the FLM broker using python? i'd love to add content from a set of DS20B18 one-wire sensors to my local FLM-display.

The sensors itself are already read out by the r-pie & dumped in a local round robin database using a python script (based on http://wannabe.guru.org/scott/hobbies/temperature/ ) 
but if possible, i'd like to pipe the data to the same local FLM interface .

Do you know/ could you explain what python libraries should/could best be used for this?
And what default settings the MQTT broker uses?
I assume flm ip, port 1883,  and consistency level 1?
From your arduino code, i conclude that the payload should have the form [topic,value,"unit"] ? 

I'll keep you posted on my progress :-)

EDIT: changed title from feature request: Dallas 1 wire-publicaiton on MQTT, to support for...

**Comment by Ryton** [comment]
Partly solved, based on reading your fmlocal documentation:

topic: /sensor/<sensor id>/gauge
payload: <value> 
        [<value>] 
        [<value>, <unit>] 
        [<timestamp>, <value>, <unit>]

Now I still need a suitable python library that supports MQTT, and a small amount of custom scripting.
From what i read, paho-mqtt might be usefull. I'll investigate it later today (tonight).

**Comment by Ryton** [comment]
Status: still a bit stuck on the mqtt side

Paho-mqtt for python is installed, but a status = client.connect(FLM_ip, 1883, 60) returns me "0" -not connected-, while the FLM (mqtt server) is for sure online  Your gauges (hosted by FLM software) show internal readings, but not yet my external ones: Latest MQTT message: /sensor/<token>/gauge, [<unixtime>,149,"W"]

On the positive side: I did manage to construct a suitable topic & payload (i think) for publishing of the Dallas sensor temperatures from Python, see below. Thus, imho only the last hurdle remains...

topic =  /sensor/cellar/gauge
payload = [1433963022,20.5, "degC" ]

**Comment by Ryton** [comment]
Managed to connect to the broker!
Subscribing from Ra-Pi (or windows) from within python is working too now. :-)
Still no luck publishing the data yet.

To be continued

**Comment by Ryton** [comment]
Got it working!
A few mistakes in my MQTT understanding. Spaces in front of the topic are deadly, and so is an extra slash in the end... :-s
And last but not least:  
in python, protocol = mqtt.MQTTv31 wasnt defined, since i didnt load the whole mqtt library.
after changing these, it works like a charm (see screenshot).
![rapie_gauges](https://cloud.githubusercontent.com/assets/6223082/8115076/4f3af38a-1079-11e5-883f-c00f566ff6ae.jpg)

This issue can be closed imho. If you want, I can share the python code, but it's pretty basic.

Possible TODO's still: 
I'd like to add the bonjour service to find the FLM (broker's) ip adress, instead of hardcoding it.
based on my rrd-database, I'd like to include the publishing of hourly/daily/weekly average/min/max measured temperature values.

**Comment by Ryton** [comment]
Update: 
- Added ip-lookup service (using python-avahi) to the scripts. But now the Flukso hostname (flukso-x1234y.local) is still hardcoded ... Better, but not there yet. Is there a way to look up this hostname? (or get all avahi services as a list?)
- Moved to mysql db instead of rrd.
- Daily/hourly averages/min/max are calculated based on database entry, & published on MQTT (with retention) too.

**Comment by gebhardm** [comment]
I don't use Python; did so in the beginning, but moved to node.js because then server and client side can be kept in the same programming language, native to the browser.
The trick with the discovery is that you have to look what services serve "mqtt" as protocol:

```
 // detect mqtt publishers and create corresponding servers
 var mdnsbrowser = mdns.createBrowser(mdns.tcp("mqtt"));
```

See [flmdisplay:flmdata server](https://github.com/gebhardm/flmdisplay/blob/master/combined/serve_flmdata.js) - here actually everything you need (also the potential advertising of your sensor server) is included - why complicated, if you can do it simple ;-)
